services:
  nginx-waf:
    build: .
    image: owasp/modsecurity-crs
    container_name: nginx-waf
    ports:
      - "80:80"
    volumes:
      - ./modsecurity.conf:/etc/nginx/modsecurity.d/modsecurity.conf
      - ./crs-setup.conf:/etc/nginx/modsecurity.d/crs-setup.conf

